-- Add new internal fields columns to the internal_fields table
ALTER TABLE public.internal_fields 
ADD COLUMN parent_product_id TEXT,
ADD COLUMN nbt_num TEXT,
ADD COLUMN catalog_num TEXT,
ADD COLUMN host TEXT,
ADD COLUMN clone TEXT,
ADD COLUMN clonality TEXT,
ADD COLUMN isotype TEXT,
ADD COLUMN light_chain TEXT,
ADD COLUMN storage_temperature TEXT,
ADD COLUMN lead_time TEXT,
ADD COLUMN country_of_origin TEXT,
ADD COLUMN datasheet_url TEXT,
ADD COLUMN website_url_to_product TEXT,
ADD COLUMN price_usd NUMERIC,
ADD COLUMN product_application TEXT,
ADD COLUMN research_area TEXT,
ADD COLUMN image_url TEXT,
ADD COLUMN image_filename TEXT,
ADD COLUMN image_caption TEXT,
ADD COLUMN positive_control TEXT,
ADD COLUMN expression_system TEXT,
ADD COLUMN purification TEXT,
ADD COLUMN supplied_as TEXT;