// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqzxlufeoassbbfrvvhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxenhsdWZlb2Fzc2JiZnJ2dmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mzc3NTYsImV4cCI6MjA2ODUxMzc1Nn0.bQ95ywf3JLcajD6m3MY4iS91ZS1QGmAGSE5YqeVTTQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});